name: Publish Semantic Version Chromium Cloakbrowser Docker Image to GitHub Container Registry

on:
  push:
    tags: [v2.*]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/docker-publish-chromium-cloakbrowser.yml
    secrets: inherit
    with:
      tag: ${{ github.ref_name }}
